# Pythonベースイメージ
FROM python:3.12-slim

# 必要なツールのインストール
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    tzdata \
    && apt-get clean

ENV TZ=Asia/Tokyo

# 作業ディレクトリの設定
WORKDIR /app

# Python依存パッケージのインストール
COPY python/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# ソースコードをコピー
COPY python/ /app/

# コンテナ起動時のデフォルトコマンド
CMD ["python3", "-m", "http.server", "8000"]
